# Generated by Django 4.2.16 on 2026-01-10 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('dominio', models.CharField(db_index=True, help_text='Subdominio (ex: anacdeluxe para anacdeluxe.posvendafacil.com.br)', max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('plano', models.CharField(choices=[('basic', 'Basico'), ('pro', 'Profissional'), ('enterprise', 'Enterprise')], default='basic', max_length=50)),
                ('woo_ssh_host', models.CharField(blank=True, help_text='IP ou hostname do servidor (ex: 157.245.119.130)', max_length=200, verbose_name='SSH Host')),
                ('woo_ssh_port', models.IntegerField(default=22, verbose_name='SSH Port')),
                ('woo_ssh_user', models.CharField(blank=True, help_text='Usuario SSH (ex: root)', max_length=100, verbose_name='SSH Usuario')),
                ('woo_ssh_key_path', models.CharField(blank=True, help_text='Caminho da chave SSH (ex: ~/.ssh/id_ed25519)', max_length=500, verbose_name='SSH Key Path')),
                ('woo_db_host', models.CharField(default='127.0.0.1', max_length=200, verbose_name='DB Host')),
                ('woo_db_port', models.IntegerField(default=3306, verbose_name='DB Port')),
                ('woo_db_name', models.CharField(blank=True, max_length=100, verbose_name='DB Nome')),
                ('woo_db_user', models.CharField(blank=True, max_length=100, verbose_name='DB Usuario')),
                ('woo_db_password', models.CharField(blank=True, max_length=200, verbose_name='DB Senha')),
                ('woo_table_prefix', models.CharField(default='wp_', help_text='Prefixo das tabelas WordPress (ex: wp_)', max_length=20, verbose_name='Table Prefix')),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/logos/', verbose_name='Logo')),
                ('cor_primaria', models.CharField(default='#79aec8', help_text='Cor em hexadecimal (ex: #79aec8)', max_length=7, verbose_name='Cor Primaria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EmpresaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Proprietario'), ('admin', 'Administrador'), ('operator', 'Operador'), ('viewer', 'Visualizador')], default='operator', max_length=20, verbose_name='Funcao')),
                ('is_default', models.BooleanField(default=False, help_text='Empresa que sera selecionada automaticamente ao logar', verbose_name='Empresa Padrao')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='tenants.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario da Empresa',
                'verbose_name_plural': 'Usuarios da Empresa',
                'db_table': 'empresa_usuarios',
            },
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['slug'], name='empresas_slug_1a17f5_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['dominio'], name='empresas_dominio_8daf37_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['ativo'], name='empresas_ativo_c55b16_idx'),
        ),
        migrations.AddIndex(
            model_name='empresausuario',
            index=models.Index(fields=['usuario', 'empresa'], name='empresa_usu_usuario_779088_idx'),
        ),
        migrations.AddIndex(
            model_name='empresausuario',
            index=models.Index(fields=['usuario', 'is_default'], name='empresa_usu_usuario_f143bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='empresausuario',
            unique_together={('empresa', 'usuario')},
        ),
    ]
