# Generated by Django 4.2.16 on 2026-01-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='fv_field_nome',
            field=models.CharField(default='Nome_3', help_text='Nome do meta_key para o campo Nome (ex: Nome_3, Nome)', max_length=100, verbose_name='Campo Nome'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fv_field_tamanho',
            field=models.CharField(blank=True, default='Número_do_sapato_9', help_text='Nome do meta_key para tamanho (ex: Número_do_sapato_9). Deixe vazio se não usar.', max_length=100, verbose_name='Campo Tamanho/Sapato'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fv_field_whatsapp',
            field=models.CharField(default='Whatsapp_8', help_text='Nome do meta_key para WhatsApp (ex: Whatsapp_8, Whatsapp - DDD + Numero)', max_length=100, verbose_name='Campo WhatsApp'),
        ),
    ]
