# Generated by Django 4.2.16 on 2026-01-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_add_formvibes_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='msg_whatsapp_cart',
            field=models.TextField(default='Olá {nome}, tudo bem ??', help_text='Mensagem padrão para recuperação de carrinho. Use {nome} para inserir o nome do cliente.', verbose_name='Mensagem WhatsApp - Carrinho'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='msg_whatsapp_lead',
            field=models.TextField(default='Olá {nome}, tudo bem ??', help_text='Mensagem padrão para leads. Use {nome} para inserir o nome do lead.', verbose_name='Mensagem WhatsApp - Leads'),
        ),
    ]
