# Generated by Django 4.2.16 on 2026-02-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_add_whatsapp_message_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='msg_whatsapp_lead_cliente',
            field=models.TextField(default='Olá {nome}, que bom ter você de volta! Vimos que você já comprou conosco e temos novidades especiais pra você. Posso te ajudar?', help_text='Mensagem para leads que já são clientes. Use {nome}.', verbose_name='Mensagem WhatsApp - Lead já Cliente'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='msg_whatsapp_pedido_embalado',
            field=models.TextField(default='Olá {nome}! Seu pedido #{numero} já foi embalado e saiu da fábrica! O código de rastreio será enviado para o seu email ainda hoje à noite.', help_text='Mensagem quando pedido é embalado. Use {nome}, {numero}.', verbose_name='Mensagem WhatsApp - Pedido Embalado'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='msg_whatsapp_pedido_novo',
            field=models.TextField(default='Olá {nome}! Recebemos seu pedido #{numero}. Obrigado pela compra! Em breve você receberá atualizações sobre o envio.', help_text='Mensagem quando cliente faz uma compra. Use {nome}, {numero}, {valor}.', verbose_name='Mensagem WhatsApp - Pedido Novo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='wapi_ativo',
            field=models.BooleanField(default=True, help_text='Ativar/desativar envio automático de WhatsApp', verbose_name='WhatsApp Ativo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='wapi_instance',
            field=models.CharField(blank=True, help_text='ID da instância W-API. Deixe vazio para usar o padrão do sistema.', max_length=200, verbose_name='W-API Instância'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='wapi_token',
            field=models.CharField(blank=True, help_text='Token da W-API. Deixe vazio para usar o padrão do sistema.', max_length=200, verbose_name='W-API Token'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='msg_whatsapp_cart',
            field=models.TextField(default='Olá {nome}, tudo bem ??', help_text='Mensagem para recuperação de carrinho. Use {nome}.', verbose_name='Mensagem WhatsApp - Carrinho'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='msg_whatsapp_lead',
            field=models.TextField(default='Olá {nome}, tudo bem ??', help_text='Mensagem para leads novos (prospects). Use {nome}.', verbose_name='Mensagem WhatsApp - Lead Novo'),
        ),
    ]
