# Generated by Django 4.2.16 on 2026-03-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_add_wapi_and_message_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='woo_webhook_secret',
            field=models.CharField(blank=True, help_text='Secret do webhook WooCommerce (configurar no WooCommerce > Settings > Advanced > Webhooks)', max_length=200, verbose_name='Webhook Secret'),
        ),
    ]
