# Generated by Django 4.2.16 on 2026-03-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_add_webhook_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='msg_whatsapp_pedido_cancelado',
            field=models.TextField(default='Olá {nome}, seu pedido #{numero} foi cancelado. Se precisar de ajuda, estamos à disposição.', help_text='Mensagem quando pedido é cancelado. Use {nome}, {numero}, {valor}.', verbose_name='Mensagem WhatsApp - Pedido Cancelado'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='msg_whatsapp_pedido_concluido',
            field=models.TextField(default='Olá {nome}! Seu pedido #{numero} foi entregue! Esperamos que goste. Qualquer dúvida estamos à disposição.', help_text='Mensagem quando pedido é entregue. Use {nome}, {numero}, {valor}.', verbose_name='Mensagem WhatsApp - Pedido Concluído'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='msg_whatsapp_pedido_processando',
            field=models.TextField(default='Olá {nome}! Seu pagamento do pedido #{numero} foi confirmado! Estamos preparando seu pedido.', help_text='Mensagem quando pagamento é confirmado. Use {nome}, {numero}, {valor}.', verbose_name='Mensagem WhatsApp - Pedido Processando'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='msg_whatsapp_pedido_transito',
            field=models.TextField(default='Olá {nome}! Seu pedido #{numero} está em trânsito! Acompanhe pelo código de rastreio no seu email.', help_text='Mensagem quando pedido está em trânsito. Use {nome}, {numero}, {valor}.', verbose_name='Mensagem WhatsApp - Pedido em Trânsito'),
        ),
    ]
