# Generated by Django 4.2.16 on 2026-03-03 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_add_status_message_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanciaWAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Pós-Venda, Vendas, Suporte', max_length=100)),
                ('wapi_token', models.CharField(max_length=200, verbose_name='Token')),
                ('wapi_instance', models.CharField(max_length=200, verbose_name='Instância')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instancias_wapi', to='tenants.empresa')),
            ],
            options={
                'verbose_name': 'Instância W-API',
                'verbose_name_plural': 'Instâncias W-API',
                'db_table': 'instancias_wapi',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='instancia_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.instanciawapi', verbose_name='Instância - Carrinho'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='instancia_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.instanciawapi', verbose_name='Instância - Lead Novo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='instancia_lead_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.instanciawapi', verbose_name='Instância - Lead Cliente'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='instancia_pedido_cancelado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.instanciawapi', verbose_name='Instância - Pedido Cancelado'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='instancia_pedido_concluido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.instanciawapi', verbose_name='Instância - Pedido Concluído'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='instancia_pedido_embalado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.instanciawapi', verbose_name='Instância - Pedido Embalado'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='instancia_pedido_novo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.instanciawapi', verbose_name='Instância - Pedido Novo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='instancia_pedido_processando',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.instanciawapi', verbose_name='Instância - Pedido Processando'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='instancia_pedido_transito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.instanciawapi', verbose_name='Instância - Pedido em Trânsito'),
        ),
    ]
