# Generated by Django 4.2.16 on 2026-03-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_add_instancia_wapi_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='msg_ativa_cart',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='msg_ativa_lead',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='msg_ativa_lead_cliente',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='msg_ativa_pedido_cancelado',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='msg_ativa_pedido_concluido',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='msg_ativa_pedido_embalado',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='msg_ativa_pedido_novo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='msg_ativa_pedido_processando',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='msg_ativa_pedido_transito',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
