# Generated by Django 4.2.16 on 2026-03-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_add_msg_ativa_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='bling_client_id',
            field=models.CharField(blank=True, help_text='Client ID do app Bling (API V3)', max_length=200, verbose_name='Bling Client ID'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='bling_client_secret',
            field=models.CharField(blank=True, help_text='Client Secret do app Bling (API V3)', max_length=200, verbose_name='Bling Client Secret'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='bling_situacao_transito_id',
            field=models.CharField(blank=True, help_text='ID da situação "Em Trânsito" no Bling (varia por conta)', max_length=50, verbose_name='ID Situação Em Trânsito'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='meta_access_token',
            field=models.TextField(blank=True, help_text='Token de acesso permanente da Meta Cloud API', verbose_name='Access Token Meta'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='meta_phone_number_id',
            field=models.CharField(blank=True, help_text='ID do número de telefone no Meta Business', max_length=100, verbose_name='Phone Number ID'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='meta_template_transito',
            field=models.CharField(blank=True, default='pedido_em_transito', help_text='Nome do template aprovado no WhatsApp Manager', max_length=100, verbose_name='Template Em Trânsito'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='meta_waba_id',
            field=models.CharField(blank=True, help_text='WhatsApp Business Account ID', max_length=100, verbose_name='WABA ID'),
        ),
    ]
