# Generated by Django 4.2.16 on 2026-03-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_empresa_bling_client_id_empresa_bling_client_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='bling_situacao_cancelado_id',
            field=models.CharField(blank=True, help_text='ID da situação "Cancelado" no Bling (varia por conta)', max_length=50, verbose_name='ID Situação Cancelado'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='bling_situacao_concluido_id',
            field=models.CharField(blank=True, help_text='ID da situação "Concluído" no Bling (varia por conta)', max_length=50, verbose_name='ID Situação Concluído'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='bling_situacao_embalado_id',
            field=models.CharField(blank=True, help_text='ID da situação "Embalado" no Bling (varia por conta)', max_length=50, verbose_name='ID Situação Embalado'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='bling_situacao_processando_id',
            field=models.CharField(blank=True, help_text='ID da situação "Processando" no Bling (varia por conta)', max_length=50, verbose_name='ID Situação Processando'),
        ),
    ]
