# Generated by Django 4.2.16 on 2026-03-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_add_bling_situacao_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='meta_cupom_codigo',
            field=models.CharField(blank=True, default='cupom10', help_text='Codigo do cupom para os templates Meta (ex: cupom10)', max_length=50, verbose_name='Codigo do Cupom'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='meta_cupom_desconto',
            field=models.CharField(blank=True, default='10', help_text='Percentual de desconto (ex: 10)', max_length=10, verbose_name='% Desconto'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='meta_cupom_validade',
            field=models.CharField(blank=True, default='dia 23/07/2026', help_text='Data de validade do cupom (ex: dia 23/07/2026)', max_length=50, verbose_name='Validade do Cupom'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='meta_template_cart',
            field=models.CharField(blank=True, default='cupom_cliente_tarragona', help_text='Template para recuperacao de carrinho. Params: {{1}}=nome, {{2}}=cupom, {{3}}=desconto, {{4}}=validade', max_length=100, verbose_name='Template Carrinho Abandonado'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='meta_template_lead_cliente',
            field=models.CharField(blank=True, default='promocoes_tarragona_leads_clientes', help_text='Template para leads que ja sao clientes. Params: {{1}}=nome, {{2}}=cupom, {{3}}=desconto, {{4}}=validade', max_length=100, verbose_name='Template Lead Cliente'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='meta_template_lead_nao_cliente',
            field=models.CharField(blank=True, default='promocoes_tarragona_leads_nao_clientes', help_text='Template para leads que nunca compraram. Params: {{1}}=nome, {{2}}=cupom, {{3}}=desconto, {{4}}=validade', max_length=100, verbose_name='Template Lead Nao Cliente'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='meta_template_transito',
            field=models.CharField(blank=True, default='pedido_em_transito', help_text='Nome do template aprovado no WhatsApp Manager', max_length=100, verbose_name='Template Em Transito'),
        ),
    ]
