# Generated by Django 4.2.16 on 2026-03-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_add_meta_templates_cupom_and_mensagem_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='meta_template_cliente_inativo',
            field=models.CharField(blank=True, default='cupom_cliente_tarragona', help_text='Template para reativacao de clientes inativos. Params: {{1}}=nome, {{2}}=cupom, {{3}}=desconto, {{4}}=validade', max_length=100, verbose_name='Template Cliente Inativo'),
        ),
    ]
