# Generated by Django 4.2.16 on 2026-03-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_empresa_meta_template_cliente_inativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='meta_template_lead_nao_cliente_cupom',
            field=models.CharField(blank=True, default='cupom_tarragona_leads_nao_clientes', help_text='Template com cupom para leads que nunca compraram (primeira compra). Params: {{1}}=nome, {{2}}=cupom, {{3}}=desconto, {{4}}=validade', max_length=100, verbose_name='Template Lead Nao Cliente (com cupom)'),
        ),
    ]
