# Generated by Django 4.2.16 on 2026-03-01 23:04

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0006_add_billing_address_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrinhoAbandonado',
            fields=[
            ],
            options={
                'verbose_name': 'Carrinho Abandonado',
                'verbose_name_plural': 'Carrinhos Abandonados',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('customers.cart',),
        ),
        migrations.CreateModel(
            name='Comprador',
            fields=[
            ],
            options={
                'verbose_name': 'Comprador',
                'verbose_name_plural': 'Compradores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('customers.customer',),
        ),
        migrations.CreateModel(
            name='LeadNaoComprador',
            fields=[
            ],
            options={
                'verbose_name': 'Lead Nao Comprador',
                'verbose_name_plural': 'Leads Nao Compradores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('customers.lead',),
        ),
    ]
