# Generated by Django 4.2.16 on 2025-10-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadsDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '📋 Dashboard de Importação de Leads',
                'verbose_name_plural': '📋 Dashboard de Importação de Leads',
                'managed': False,
            },
        ),
    ]
