# Generated by Django 4.2.16 on 2025-09-18 18:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_id', models.CharField(max_length=100, unique=True)),
                ('session_id', models.CharField(max_length=255)),
                ('cart_contents', models.JSONField()),
                ('cart_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('abandoned', 'Abandonado'), ('recovered', 'Recuperado'), ('converted', 'Convertido')], default='active', max_length=20)),
                ('items_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('abandoned_at', models.DateTimeField(blank=True, null=True)),
                ('recovered_at', models.DateTimeField(blank=True, null=True)),
                ('recovery_email_sent', models.BooleanField(default=False)),
                ('recovery_whatsapp_sent', models.BooleanField(default=False)),
                ('coupon_used', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'carts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('never_bought', 'Nunca Comprou'), ('first_time', 'Primeira Compra'), ('returning', 'Cliente Recorrente'), ('abandoned_only', 'Só Abandonou Carrinho'), ('inactive', 'Inativo'), ('vip', 'VIP')], default='never_bought', max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('total_orders', models.IntegerField(default=0)),
                ('completed_orders', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_carts', models.IntegerField(default=0)),
                ('abandoned_carts', models.IntegerField(default=0)),
                ('recovered_carts', models.IntegerField(default=0)),
                ('total_abandoned_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('first_purchase', models.DateTimeField(blank=True, null=True)),
                ('last_purchase', models.DateTimeField(blank=True, null=True)),
                ('last_cart_abandoned', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('days_since_last_purchase', models.IntegerField(blank=True, null=True)),
                ('purchase_frequency_days', models.IntegerField(blank=True, null=True)),
                ('preferred_purchase_hour', models.IntegerField(blank=True, null=True)),
                ('preferred_purchase_weekday', models.IntegerField(blank=True, null=True)),
                ('churn_probability', models.FloatField(default=0)),
                ('purchase_probability', models.FloatField(default=0)),
                ('lifetime_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_analyzed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['-score', '-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_customers', models.IntegerField(default=0)),
                ('new_customers', models.IntegerField(default=0)),
                ('never_bought', models.IntegerField(default=0)),
                ('first_time', models.IntegerField(default=0)),
                ('returning', models.IntegerField(default=0)),
                ('abandoned_only', models.IntegerField(default=0)),
                ('inactive', models.IntegerField(default=0)),
                ('vip', models.IntegerField(default=0)),
                ('total_carts', models.IntegerField(default=0)),
                ('abandoned_carts', models.IntegerField(default=0)),
                ('recovered_carts', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('abandoned_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('conversion_rate', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'customer_analysis',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('order_number', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('items_count', models.IntegerField(default=0)),
                ('payment_method', models.CharField(max_length=100, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.customer')),
                ('related_cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.cart')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['status', '-score'], name='customers_status_8e4a1d_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email', 'phone'], name='customers_email_5bdbe5_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['-last_activity'], name='customers_last_ac_39b084_idx'),
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='customers.customer'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['customer', '-created_at'], name='carts_custome_3ebc6c_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['status', '-created_at'], name='carts_status_270aa2_idx'),
        ),
    ]
