# Generated by Django 4.2.16 on 2025-09-29 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='coupon_used',
            new_name='recovery_coupon',
        ),
        migrations.AddField(
            model_name='cart',
            name='recovered_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovered_from_cart', to='customers.order'),
        ),
        migrations.AddField(
            model_name='cart',
            name='recovery_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='recovery_email_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='recovery_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cart',
            name='recovery_whatsapp_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='was_recovered',
            field=models.BooleanField(default=False),
        ),
    ]
