# Generated by Django 4.2.16 on 2025-10-13 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_coupon_used_cart_recovery_coupon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('whatsapp', models.CharField(db_index=True, max_length=20)),
                ('numero_sapato', models.CharField(db_index=True, max_length=10)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.CharField(choices=[('new', 'Novo'), ('contacted', 'Contactado'), ('customer', 'É Cliente'), ('potential', 'Potencial'), ('lost', 'Perdido')], default='new', max_length=20)),
                ('is_customer', models.BooleanField(default=False)),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('whatsapp_sent_date', models.DateTimeField(blank=True, null=True)),
                ('contact_attempts', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('converted_to_customer', models.BooleanField(default=False)),
                ('conversion_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_lead', to='customers.order')),
                ('related_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='customers.customer')),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['whatsapp', 'numero_sapato'], name='leads_whatsap_b57133_idx'), models.Index(fields=['status', '-created_at'], name='leads_status_dcd0ad_idx')],
            },
        ),
    ]
