# Generated by Django 4.2.16 on 2026-01-10 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('customers', '0003_lead'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cart',
            name='carts_custome_3ebc6c_idx',
        ),
        migrations.RemoveIndex(
            model_name='cart',
            name='carts_status_270aa2_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customers_status_8e4a1d_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customers_email_5bdbe5_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_whatsap_b57133_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_status_dcd0ad_idx',
        ),
        migrations.AddField(
            model_name='cart',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='tenants.empresa'),
        ),
        migrations.AddField(
            model_name='customer',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='tenants.empresa'),
        ),
        migrations.AddField(
            model_name='lead',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='tenants.empresa'),
        ),
        # Campos whatsapp_auto_* ja existem no banco, removidos da migracao
        migrations.AddField(
            model_name='order',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tenants.empresa'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='checkout_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='lead',
            name='form_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['empresa', 'customer', '-created_at'], name='carts_empresa_3226b6_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['empresa', 'status', '-created_at'], name='carts_empresa_0721bd_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['empresa', 'status', '-score'], name='customers_empresa_167360_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['empresa', 'email'], name='customers_empresa_622012_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['empresa', 'phone'], name='customers_empresa_826a68_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['empresa', 'whatsapp', 'numero_sapato'], name='leads_empresa_eef5fd_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['empresa', 'status', '-created_at'], name='leads_empresa_845765_idx'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('empresa', 'checkout_id'), name='unique_cart_checkout_per_empresa'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('empresa', 'email'), name='unique_customer_email_per_empresa'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(fields=('empresa', 'form_id'), name='unique_lead_form_per_empresa'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('empresa', 'order_id'), name='unique_order_id_per_empresa'),
        ),
    ]
