# Generated by Django 4.2.16 on 2026-01-10 21:58

from django.db import migrations


def populate_empresa(apps, schema_editor):
    """
    Cria empresa padrao e vincula todos os registros existentes
    """
    Empresa = apps.get_model('tenants', 'Empresa')
    Customer = apps.get_model('customers', 'Customer')
    Cart = apps.get_model('customers', 'Cart')
    Order = apps.get_model('customers', 'Order')
    Lead = apps.get_model('customers', 'Lead')

    # Criar empresa padrao se nao existir
    empresa, created = Empresa.objects.get_or_create(
        slug='anacdeluxe',
        defaults={
            'nome': 'Anac Deluxe',
            'dominio': 'anacdeluxe',
            'ativo': True,
            'plano': 'pro',
            'woo_ssh_host': '157.245.119.130',
            'woo_ssh_user': 'root',
            'woo_ssh_key_path': '~/.ssh/id_ed25519',
            'woo_db_host': '127.0.0.1',
            'woo_db_port': 3306,
            'woo_table_prefix': 'wp_',
        }
    )

    if created:
        print(f'Empresa criada: {empresa.nome}')
    else:
        print(f'Empresa existente: {empresa.nome}')

    # Vincular todos os registros existentes
    customers_updated = Customer.objects.filter(empresa__isnull=True).update(empresa=empresa)
    print(f'Customers vinculados: {customers_updated}')

    carts_updated = Cart.objects.filter(empresa__isnull=True).update(empresa=empresa)
    print(f'Carts vinculados: {carts_updated}')

    orders_updated = Order.objects.filter(empresa__isnull=True).update(empresa=empresa)
    print(f'Orders vinculados: {orders_updated}')

    leads_updated = Lead.objects.filter(empresa__isnull=True).update(empresa=empresa)
    print(f'Leads vinculados: {leads_updated}')


def reverse_populate(apps, schema_editor):
    """
    Nao reverter - dados ficariam orfaos
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_cart_carts_custome_3ebc6c_idx_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_empresa, reverse_populate),
    ]
