# Generated by Django 4.2.16 on 2026-03-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_populate_empresa'),
    ]

    operations = [
        # Novos campos de endereco no Customer
        migrations.AddField(
            model_name='customer',
            name='billing_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='customer',
            name='billing_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='customer',
            name='billing_postcode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='customer',
            name='billing_state',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Estado'),
        ),
        # Campos de Lead que ja existem no DB - registrar apenas no state
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='lead',
                    name='whatsapp_auto_sent_count',
                    field=models.IntegerField(default=0),
                ),
                migrations.AddField(
                    model_name='lead',
                    name='whatsapp_auto_status',
                    field=models.CharField(blank=True, max_length=50, null=True),
                ),
                migrations.AddField(
                    model_name='lead',
                    name='whatsapp_error_message',
                    field=models.TextField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='lead',
                    name='whatsapp_has_conversation',
                    field=models.BooleanField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='lead',
                    name='whatsapp_last_check',
                    field=models.DateTimeField(blank=True, null=True),
                ),
            ],
            database_operations=[],
        ),
    ]
