# Generated by Django 4.2.16 on 2026-03-07 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_add_meta_templates_cupom_and_mensagem_whatsapp'),
        ('customers', '0006_add_billing_address_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('lead', 'Lead Novo (nao cliente)'), ('lead_cliente', 'Lead Ja Cliente'), ('cart', 'Carrinho Abandonado'), ('pedido_novo', 'Pedido Novo'), ('pedido_processando', 'Pedido Processando'), ('pedido_embalado', 'Pedido Embalado'), ('pedido_transito', 'Pedido em Transito'), ('pedido_concluido', 'Pedido Concluido'), ('pedido_cancelado', 'Pedido Cancelado')], max_length=30)),
                ('canal', models.CharField(choices=[('meta', 'Meta Cloud API'), ('wapi', 'W-API')], max_length=10)),
                ('status', models.CharField(choices=[('enviado', 'Enviado'), ('falha', 'Falha'), ('entregue', 'Entregue'), ('lido', 'Lido')], default='enviado', max_length=20)),
                ('destinatario_nome', models.CharField(max_length=200)),
                ('destinatario_telefone', models.CharField(max_length=20)),
                ('template_name', models.CharField(blank=True, help_text='Nome do template Meta (se canal=meta)', max_length=100)),
                ('template_params', models.JSONField(blank=True, default=list, help_text='Parametros do template Meta')),
                ('mensagem_texto', models.TextField(blank=True, help_text='Texto da mensagem (se canal=wapi)')),
                ('error_message', models.TextField(blank=True)),
                ('api_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_whatsapp', to='customers.cart')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_whatsapp', to='customers.customer')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_whatsapp', to='tenants.empresa')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_whatsapp', to='customers.lead')),
            ],
            options={
                'verbose_name': 'Mensagem WhatsApp',
                'verbose_name_plural': 'Mensagens WhatsApp',
                'db_table': 'mensagens_whatsapp',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['empresa', 'tipo', '-created_at'], name='mensagens_w_empresa_67178e_idx'), models.Index(fields=['empresa', 'canal', '-created_at'], name='mensagens_w_empresa_039212_idx'), models.Index(fields=['destinatario_telefone', '-created_at'], name='mensagens_w_destina_d96091_idx')],
            },
        ),
    ]
