# Generated by Django 4.2.16 on 2026-03-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_add_meta_templates_cupom_and_mensagem_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagemwhatsapp',
            name='tipo',
            field=models.CharField(choices=[('lead', 'Lead Novo (nao cliente)'), ('lead_cliente', 'Lead Ja Cliente'), ('cart', 'Carrinho Abandonado'), ('cliente_inativo', 'Cliente Inativo (reativacao)'), ('pedido_novo', 'Pedido Novo'), ('pedido_processando', 'Pedido Processando'), ('pedido_embalado', 'Pedido Embalado'), ('pedido_transito', 'Pedido em Transito'), ('pedido_concluido', 'Pedido Concluido'), ('pedido_cancelado', 'Pedido Cancelado')], max_length=30),
        ),
    ]
