# Generated by Django 4.2.16 on 2026-03-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_add_meta_templates_cupom_and_mensagem_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagemwhatsapp',
            name='tipo',
            field=models.CharField(choices=[('lead', 'Lead Novo (nao cliente)'), ('lead_cliente', 'Lead Ja Cliente'), ('cart', 'Carrinho Abandonado'), ('cliente_inativo', 'Cliente Inativo (reativacao)'), ('pedido_novo', 'Pedido Novo'), ('pedido_processando', 'Pedido Processando'), ('pedido_embalado', 'Pedido Embalado'), ('pedido_transito', 'Pedido em Transito'), ('pedido_concluido', 'Pedido Concluido'), ('pedido_cancelado', 'Pedido Cancelado'), ('resposta_cliente', 'Resposta do Cliente')], max_length=30),
        ),
        migrations.AddField(
            model_name='mensagemwhatsapp',
            name='meta_message_id',
            field=models.CharField(blank=True, db_index=True, help_text='WAMID da Meta (para rastrear status)', max_length=200),
        ),
        migrations.AddField(
            model_name='mensagemwhatsapp',
            name='entregue_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensagemwhatsapp',
            name='lido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensagemwhatsapp',
            name='respondido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensagemwhatsapp',
            name='respondido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensagemwhatsapp',
            name='resposta_texto',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mensagemwhatsapp',
            name='clicou_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensagemwhatsapp',
            name='clicou_link_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='mensagemwhatsapp',
            index=models.Index(fields=['meta_message_id'], name='mensagens_w_meta_me_idx'),
        ),
    ]
