# Generated by Django 4.2.16 on 2026-03-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0009_alter_mensagemwhatsapp_tipo"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="mensagemwhatsapp",
            new_name="mensagens_w_meta_me_ddc82f_idx",
            old_name="mensagens_w_meta_me_idx",
        ),
        migrations.AddField(
            model_name="mensagemwhatsapp",
            name="encaminhado_humano",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mensagemwhatsapp",
            name="encaminhado_humano_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mensagemwhatsapp",
            name="meta_message_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="wamid retornado pela Meta API",
                max_length=200,
            ),
        ),
    ]
