# Generated by Django 4.2.16 on 2026-03-08 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_mensagemwhatsapp_tipo'),
        ('customers', '0010_add_meta_message_tracking'),
    ]

    operations = [
    ]
