# Generated by Django 4.2.16 on 2026-03-08 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0014_add_meta_webhook_fields'),
        ('customers', '0012_alter_mensagemwhatsapp_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraComunicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Carrinho abandonado - etapa 1', max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('gatilho', models.CharField(choices=[('cart_abandoned', 'Carrinho Abandonado'), ('cart_high_value', 'Carrinho Alto Valor (> R$X)'), ('lead_new', 'Lead Novo (form preenchido)'), ('lead_repeat_form', 'Lead Preencheu Form Novamente'), ('customer_inactive_30', 'Cliente Inativo 30 dias'), ('customer_inactive_60', 'Cliente Inativo 60 dias'), ('customer_inactive_90', 'Cliente Inativo 90+ dias'), ('customer_first_purchase', 'Primeira Compra (pós-venda)'), ('customer_repeat_purchase', 'Compra Recorrente'), ('customer_vip', 'Cliente VIP'), ('order_created', 'Pedido Criado'), ('order_processing', 'Pedido Processando'), ('order_shipped', 'Pedido Embalado'), ('order_in_transit', 'Pedido em Trânsito'), ('order_delivered', 'Pedido Entregue'), ('order_cancelled', 'Pedido Cancelado'), ('manual', 'Disparo Manual')], max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('prioridade', models.IntegerField(default=10, help_text='Menor = mais prioritário. Quando duas réguas se aplicam ao mesmo contato, a de menor número ganha.')),
                ('etapa', models.IntegerField(default=1, help_text='Etapa na sequência. Etapa 2 só dispara se etapa 1 foi enviada e não houve conversão.')),
                ('delay_horas', models.IntegerField(default=0, help_text='Horas após o gatilho para enviar. Ex: 2 = envia 2h depois do carrinho abandonado.')),
                ('horario_inicio', models.TimeField(default='09:00', help_text='Não enviar antes deste horário')),
                ('horario_fim', models.TimeField(default='20:00', help_text='Não enviar depois deste horário')),
                ('dias_semana', models.JSONField(blank=True, default=list, help_text='Dias permitidos [0=seg...6=dom]. Vazio = todos.')),
                ('condicoes', models.JSONField(blank=True, default=dict, help_text='Filtros JSON. Ex: {"min_cart_value": 50, "min_orders": 1, "max_engagement_score": 80}')),
                ('cooldown_horas', models.IntegerField(default=168, help_text='Horas mínimas entre envios da MESMA régua para o MESMO telefone. 168 = 7 dias.')),
                ('max_msgs_semana_telefone', models.IntegerField(default=3, help_text='Máximo de mensagens por semana para o MESMO telefone (todas as réguas somadas).')),
                ('max_envios_total', models.IntegerField(default=0, help_text='Máximo de vezes que esta régua envia para o mesmo contato. 0 = sem limite.')),
                ('max_envios_dia', models.IntegerField(default=50, help_text='Máximo de envios desta régua por dia (anti-spam global).')),
                ('max_ignorados_consecutivos', models.IntegerField(default=3, help_text='Se o contato ignorou N msgs consecutivas (não leu), parar de enviar. 0 = desativado.')),
                ('canal', models.CharField(choices=[('meta', 'Meta Cloud API'), ('wapi', 'W-API'), ('auto', 'Automático (Meta → W-API fallback)')], default='meta', max_length=5)),
                ('template_meta', models.CharField(blank=True, help_text='Nome do template aprovado no Meta Business', max_length=100)),
                ('template_params_map', models.JSONField(blank=True, default=list, help_text='Parâmetros do template. Ex: ["nome", "cupom", "desconto", "validade"]')),
                ('texto_wapi', models.TextField(blank=True, help_text='Texto para W-API. Variáveis: {nome}, {numero}, {valor}, {cupom}, {desconto}, {validade}')),
                ('button_url_param', models.CharField(blank=True, help_text='Campo do objeto para URL dinâmica do botão Meta. Ex: session_id', max_length=50)),
                ('usar_cupom', models.BooleanField(default=False)),
                ('cupom_codigo', models.CharField(blank=True, max_length=50)),
                ('cupom_desconto', models.CharField(blank=True, max_length=10)),
                ('cupom_validade', models.CharField(blank=True, max_length=50)),
                ('total_enviados', models.IntegerField(default=0)),
                ('total_entregues', models.IntegerField(default=0)),
                ('total_lidos', models.IntegerField(default=0)),
                ('total_respondidos', models.IntegerField(default=0)),
                ('total_convertidos', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_comunicacao', to='tenants.empresa')),
                ('instancia_wapi', models.ForeignKey(blank=True, help_text='Instância W-API específica. Vazio = usa fallback da empresa.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.instanciawapi')),
            ],
            options={
                'verbose_name': 'Régua de Comunicação',
                'verbose_name_plural': 'Réguas de Comunicação',
                'db_table': 'regras_comunicacao',
                'ordering': ['empresa', 'gatilho', 'etapa', 'prioridade'],
            },
        ),
        migrations.CreateModel(
            name='FilaEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=200)),
                ('agendar_para', models.DateTimeField(help_text='Quando enviar (respeita horário comercial da régra).')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviando', 'Enviando'), ('enviado', 'Enviado'), ('falha', 'Falha'), ('cancelado', 'Cancelado'), ('bloqueado', 'Bloqueado (blacklist/capping)')], default='pendente', max_length=10)),
                ('erro', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fila_envios', to='customers.cart')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fila_envios', to='customers.customer')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fila_envios', to='tenants.empresa')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fila_envios', to='customers.lead')),
                ('mensagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fila_envio', to='customers.mensagemwhatsapp')),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fila_envios', to='comunicacao.regracomunicacao')),
            ],
            options={
                'verbose_name': 'Item na Fila',
                'verbose_name_plural': 'Fila de Envio',
                'db_table': 'fila_envio',
                'ordering': ['agendar_para'],
            },
        ),
        migrations.CreateModel(
            name='EventoRecebido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cart.abandoned', 'Carrinho Abandonado'), ('cart.recovered', 'Carrinho Recuperado'), ('order.created', 'Pedido Criado'), ('order.status_changed', 'Status do Pedido Mudou'), ('lead.created', 'Lead Criado'), ('customer.created', 'Cliente Criado'), ('customer.updated', 'Cliente Atualizado')], max_length=30)),
                ('plataforma', models.CharField(choices=[('woocommerce', 'WooCommerce'), ('shopify', 'Shopify'), ('nuvemshop', 'Nuvemshop'), ('api', 'API Genérica'), ('webhook', 'Webhook'), ('manual', 'Manual')], default='api', max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('processado', models.BooleanField(default=False)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
                ('erro', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='customers.cart')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='customers.customer')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='tenants.empresa')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='customers.lead')),
            ],
            options={
                'verbose_name': 'Evento Recebido',
                'verbose_name_plural': 'Eventos Recebidos',
                'db_table': 'eventos_recebidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContatoBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(db_index=True, max_length=20)),
                ('motivo', models.CharField(choices=[('opt_out', 'Opt-out (pediu para parar)'), ('spam_report', 'Reportou spam'), ('blocked', 'Bloqueou o número'), ('invalid_number', 'Número inválido'), ('too_many_ignored', 'Ignorou muitas mensagens'), ('manual', 'Bloqueio manual')], max_length=20)),
                ('detalhes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist', to='tenants.empresa')),
            ],
            options={
                'verbose_name': 'Contato Bloqueado',
                'verbose_name_plural': 'Contatos Bloqueados',
                'db_table': 'contato_blacklist',
            },
        ),
        migrations.AddIndex(
            model_name='regracomunicacao',
            index=models.Index(fields=['empresa', 'gatilho', 'ativo'], name='regras_comu_empresa_03f12c_idx'),
        ),
        migrations.AddIndex(
            model_name='regracomunicacao',
            index=models.Index(fields=['empresa', 'ativo', 'prioridade'], name='regras_comu_empresa_227d31_idx'),
        ),
        migrations.AddIndex(
            model_name='filaenvio',
            index=models.Index(fields=['status', 'agendar_para'], name='fila_envio_status_75b7cb_idx'),
        ),
        migrations.AddIndex(
            model_name='filaenvio',
            index=models.Index(fields=['empresa', 'telefone', '-created_at'], name='fila_envio_empresa_bea70f_idx'),
        ),
        migrations.AddIndex(
            model_name='filaenvio',
            index=models.Index(fields=['empresa', 'regra', 'status'], name='fila_envio_empresa_bc1505_idx'),
        ),
        migrations.AddIndex(
            model_name='eventorecebido',
            index=models.Index(fields=['empresa', 'tipo', '-created_at'], name='eventos_rec_empresa_f0aa10_idx'),
        ),
        migrations.AddIndex(
            model_name='eventorecebido',
            index=models.Index(fields=['processado', '-created_at'], name='eventos_rec_process_8ac9f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='contatoblacklist',
            constraint=models.UniqueConstraint(fields=('empresa', 'telefone'), name='unique_blacklist_per_empresa'),
        ),
    ]
