# Generated by Django 4.2.16 on 2026-03-04 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0009_empresa_bling_client_id_empresa_bling_client_secret_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bling_token', to='tenants.empresa')),
            ],
            options={
                'verbose_name': 'Token Bling',
                'verbose_name_plural': 'Tokens Bling',
                'db_table': 'bling_tokens',
            },
        ),
        migrations.CreateModel(
            name='BlingPedidoEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bling_pedido_id', models.CharField(max_length=100)),
                ('numero_pedido', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('nome_cliente', models.CharField(blank=True, max_length=200)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('canal', models.CharField(choices=[('meta', 'Meta Cloud API'), ('wapi', 'W-API')], default='meta', help_text='Canal usado para envio', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bling_pedidos_enviados', to='tenants.empresa')),
            ],
            options={
                'verbose_name': 'Pedido Bling Enviado',
                'verbose_name_plural': 'Pedidos Bling Enviados',
                'db_table': 'bling_pedidos_enviados',
                'ordering': ['-enviado_em'],
                'unique_together': {('empresa', 'bling_pedido_id')},
            },
        ),
    ]
