# Generated by Django 4.2.16 on 2026-03-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_add_bling_situacao_fields'),
        ('bling', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blingpedidoenviado',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='blingpedidoenviado',
            name='status',
            field=models.CharField(default='em-transito', help_text='Status que gerou o envio (processando, embalado, em-transito, concluido, cancelado)', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='blingpedidoenviado',
            unique_together={('empresa', 'bling_pedido_id', 'status')},
        ),
    ]
